image:
  - Visual Studio 2019

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,gcc-core,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,make,unzip,automake,automake1.16,autoconf,autoconf2.5,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,python3,libtool,wget,liblzma-devel,libcurl-devel
    CYG_ROOT: C:\cygwin64
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_SETUP: setup-x86_64.exe
    BASH: C:\cygwin64\bin\bash
    CC: gcc

# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'

init:
  - git config --global core.autocrlf true

install:
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "https://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
  #- $env.BASH -lc "$env:CYG_SETUP --no-shortcuts --only-site --root \"%CYG_ROOT%\" --site \"%CYG_MIRROR%\" --local-package-dir \"%CYG_CACHE%\" --packages \"%CYG_PACKAGES%\" --upgrade-also"
  - $env:CYG_SETUP --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also


build_script:
  - set HOME=.
  - $env.BASH -lc "git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex"
  - $env.BASH -lc "python3 ./ci/windows_xxhsum_fix.py"
  - $env.BASH -lc "cd mccortex && make all"
