image:
  - Visual Studio 2019

services:
  - mongodb

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,unzip,automake,automake1.16,autoconf,autoconf2.5,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,python3,libtool,wget,liblzma-devel,libcurl-devel,R,libncurses-devel,python3-cython,python3-devel
    CYG_ROOT: C:\cygwin64
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_SETUP: setup-x86_64.exe
    BASH: C:\cygwin64\bin\bash
    CC: gcc


# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'
clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - set HOME=.
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "https://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
  - '%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also'
  - '%BASH% -lc "which pip"'
  - '%BASH% -lc "python3 -m ensurepip"'
  - '%BASH% -lc "pip3 install --upgrade pip"'
  - '%BASH% -lc "which pip"'
  - '%BASH% -lc "which pip3"'
  - '%BASH% -lc "pip3 install tox"'
  - '%BASH% -lc "ls -lh"'


build: off

test_script:
  - set HOME=.
  #- '%BASH% -lc "tox -e py3"'
  - '%BASH% -lc "echo skip tests to save time while testing pyinstaller"'

# This should be before_deploy, once there's a deploy setion added. Like this for now for testing
after_test:
  - set HOME=.
  - '%BASH% -lc "pip3 install pypiwin32==219"'
  - '%BASH% -lc "git clone -b develop https://github.com/pyinstaller/pyinstaller.git"'
  - '%BASH% -lc "cd pyinstaller/bootloader && python3 ./waf all && cd .. && pip3 install ."' 
  #- '%BASH% -lc "pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz"'
  - '%BASH% -lc "git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex"'
  - '%BASH% -lc "cd mccortex/libs/htslib && git checkout bcf9bff178f81c9c1cf3a052aeb6cbe32fe5fdcc"'
  - '%BASH% -lc "cd mccortex/libs/bcftools && git checkout b406a3906b153faa8bec0a53df07b2adf18a3052"'
  - '%BASH% -lc "cd mccortex/libs/samtools && git checkout 2d4907cf9a34ccf7cde60143158b39e1cb40ac0c"'
  - '%BASH%  -lc "python3 ./ci/windows_xxhsum_fix.py"'
  - '%BASH%  -lc "cd mccortex && make all && make tests"'
  - '%BASH%  -lc "cd dist && pyinstaller --workpath=./pyinstaller_build/binary_cache --distpath=./pyinstaller_build mykrobe_atlas_pyinstaller.spec"'


