image:
  - Visual Studio 2019


install:
  - set HOME=.
  - set MSYSTEM=MINGW64
  - set PATH=C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%
  - set MINGWPREFIX=x86_64-w64-mingw32
  - "sh -lc \"pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-bzip2 mingw-w64-x86_64-xz mingw-w64-x86_64-curl\""



build_script:
  - set HOME=.
  - set MSYSTEM=MINGW64
  - set PATH=C:/msys64/usr/bin;C:/msys64/mingw64/bin;%PATH%
  - set MINGWPREFIX=x86_64-w64-mingw32
    #- set CC=gcc
  - "sh -c \"git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex\""
  - "sh -c \"python ci/windows_xxhsum_fix.py\""
  - cmd: dir
  - cmd: chdir
  - "sh -c \"cd mccortex/libs/sort_r && make\""
  - "sh -lc \"cd mccortex/libs/seq-align/libs/string_buffer && make\""
  - "sh -c \"cd mccortex/libs/seq-align/libs/seq_file && make\""
  #- "sh -c \"cd mccortex/libs/seq-align/libs && make\""
  - "sh -lc \"cd mccortex/libs/htslib && git checkout 1832d3a1b75133e55fb6abffc3f50f8a6ed5ceae && aclocal && autoheader && autoconf && ./configure && make && make install\""
  - "sh -lc \"cd mccortex/libs/seq_file && make\""
  - cmd: dir
  - "sh -lc \"cd mccortex && make all\""

#build_script:
#  - make

#test_script:
#- "sh -lc \"make test-shlib-exports && make test\""
