image:
  - Visual Studio 2019

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,gcc-core,unzip,automake,autoconf,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,python3,libtool,wget,liblzma-devel,libcurl-devel
    CYG_ROOT: C:\cygwin
    CYG_CACHE: C:\cygwin\var\cache\setup
    CYG_SETUP: setup-x86.exe
    BASH: C:\cygwin\bin\bash
    CC: gcc

# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'
clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "https://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
#  - C:\cygwin64\bin\bash -lc "%CYG_SETUP% --no-shortcuts --only-site --root \"%CYG_ROOT%\" --site \"%CYG_MIRROR%\" --local-package-dir \"%CYG_CACHE%\" --packages \"%CYG_PACKAGES%\" --upgrade-also"
  - '%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also'


build_script:
  - set HOME=.
  - '%BASH% -lc "git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex"'
  - '%BASH% -lc "cd mccortex/libs/htslib && git checkout develop && git pull"'
  - '%BASH% -lc "cd mccortex/libs/bcftools && git checkout develop && git pull"'
  - '%BASH%  -lc "python3 ./ci/windows_xxhsum_fix.py"'
  - '%BASH%  -lc "cd mccortex && make all"'
