language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - brew update
    - brew tap mongodb/brew
    - brew update
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    - ./ci/download_data.sh
    - pip3 install .
    - pip3 install pyinstaller
    - cd dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../


install:
- pip3 install cython
- pip3 install requests
- travis_retry pip3 install tox
- ./ci/download_data.sh
script: tox -e $TOXENV

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: O9w1IGrDjK2OOQDsKrv0nPcMYi9vhKOzZzi2qog4k6zYfHOQnFMslGgmsUN3OzlT5e3FYeYZRzKtsSLdnOGWLlK6dnMyXge09ILTPoV/HwTj9diAl5npwBtKi3WY7nUOAf/xIaQ4hw6WJ9005jSNs2zgBealEYePi52EBFuXOwR5LtgAYPi6ZmNVIlaNdNrEaGuXi3y4Lixb1fXDBDPPO2YH97zytsh+Nxx0+moT8G0l97GfLdwshp6Sj6JoFZ9PaTzStpafY6IhI8g0HWtpRIbKKR9Liv1bE0yF32QYgu5Ih1yGq0rBHRTMRvgh95gMiK+6T5is3VfInTEthzMPAkGA+27Fz4sLToXwWJpKQzd83Y/BV7oFrd1yRc8Qt6FdnvSKXqM8zGdOgyFeI1EJKLI3Z/QQ6iZDf+G7ii/wnlWVmRNRPspgRc6iyR1u/dgPtj2tbs4tOGn6Q/JBQNR5bJZ48w8ZmDc1DkiHr1/KMey0p7c3+nlCkRyaI8MeMkutRZXqP3VYz4tXdhfn6ATkFQRVOoJWKJFbF5ceoEQm7EptLZ55QniUPGuG2c3/kAYvoulRE7/KhH9gO2hRRo/RegiJL32PcXf2VngtNyGSEc+z0Puo9vz7QhidkY0qxM5GGmR2KQw4K5AE2Gwld5PnzUoJFc0aNcqMPyYLeT3KD+4=
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    repo: Mykrobe-tools/mykrobe

notifications:
  email: false
