language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - brew update
    - brew tap mongodb/brew
    - brew update
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    - ./ci/download_data.sh
    - pip3 install .
    - pip3 install pyinstaller
    - cd dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../


install:
- pip3 install cython
- pip3 install requests
- travis_retry pip3 install tox
- ./ci/download_data.sh
script: tox -e $TOXENV

deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  api_key:
    secure: K0UaMS43pAhHa1Ei/TJ7Y0sL8CVOZNZD5lXwQ/r2AS6apWamrl/C81q+NlJ95Wr9H5qbSGOi0MLCOxikz/RMTWYeOgaC91HKx9bpR4TFYdaNhmjtxw37xIsP06AHS6Bpind4nDxBh94sn/KX6iqMoR+SWjh8KVAplKbVcl+jEZj5kNYO/1wGgDxoLLQ7E75pONxncBJUte8g1wPGmI1c1DAfz9OBWEPClMlTOQ/NSK8Ve030DR9q8LDSkgOmbGx8/gay9S1jqyyqYPZgArhO9Q9/ls0rjxqhNshr5iTljpokxeNT3A3xBsdFZ4QsTgI3PmTGutl4g6d4Pnyz723e+Kwb52wkfH9+lZN5fHGwUAd+gQhZZhrvDRgWzG/N087/2QKxaTgVlRqFS+rG5JyWzQyFUmndnAOxIArDpvq7W3eaPjn0/FSfctOrO+HzJMI+zFWEhu4PjfZnr3GIN15/eisbNdapdM4O1bpyshLrVFVw05fOskSmctQ84qYqQpV3O09RQA4no0pUIXgbP2hig197TMJiCOdlUzCb4Aw3toP9aECvMqXCxG59L2HrZDh8TKSbIdQ0pblrDCXqeKeEs4JviZnJwemYuMoYhHSGbNcrfGgsb6uP1AmG0bfFlG8amKcfkzQrYKhYjfRHA6U34S3OJNz8oz9xGpeaP1AgAdQ=
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    repo: Mykrobe-tools/mykrobe

notifications:
  email: false
