language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - brew update
    - brew tap mongodb/brew
    - brew update
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    - ./ci/download_data.sh
    - pip3 install .
    - pip3 install pyinstaller
    - cd dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../


install:
- pip3 install cython
- pip3 install requests
- travis_retry pip3 install tox
- ./ci/download_data.sh
script: tox -e $TOXENV

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
  user: $GITHUB_USER
  password: $GITHUB_PWD
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    repo: Mykrobe-tools/mykrobe

notifications:
  email: false
