language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - brew update
    - brew tap mongodb/brew
    - brew update
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    - ./ci/download_data.sh
    - pip3 install .
    - pip3 install pyinstaller
    - cd dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../


install:
- pip3 install cython
- pip3 install requests
- travis_retry pip3 install tox
- ./ci/download_data.sh
script: tox -e $TOXENV

deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  api_key:
    secure: jIQNq0mvrwn/Dyp8b7Ebza0PwldeLb0yPqQ0Kx7yoGvFapQUezoNqBIk8eNcVFGzu1YvYDzT6q9ltfoHsRSPOhANgqQ0N6HSCWxSTmzKgtP0j5sEJ9DgmrA26iec6BAiz1Nwa1+CsRemzOpOpI1Gv9ApgXDRAtHNskDnJIfMNaQdXuAQiv1bAYBUn2qaMT/1/C5lhjoOoj5NGA5IGxAlsP7m6utulOo+tGAeehlJvn+ST4U/U9GpzF+AMrXrV0il6G4RsJTNC6gc0F1ElR1zjxMuz6cC2WEjtD/R/Y6jd++5cB4ps/KU9Iqk7Bu84wU1MeqfJAXBKWQjlPB+2bnt6snqaYFto8mYYpaPZhMOpZraxCOYxDg5OMcE7s9pbEMyIr3TyiaMXch6lemfI9JaUt/V8+hYZ/EsdvzHUCx/NU+R+4mdnQNLOKbjKoXiBSn0GuKAwjewwtRMxz13MgseGkfYHUPKdyBEoLdrXS5b+rSTFNuvK0al7Qo9GK2E7/RDSmnm3ZTggPn66EKk3DTyueCf2517emKhe7D/mcPovkbsZrG4esT/mzN0QE77ouIWIyLSKeDxoPdqgMQjpf+7akmJFkVjyq28UzGdgqJGsOcAn2oZp6DRtwNdbX5mSq7/60sUDQGH2vGMFFZXYDj/OkEZzBXEEDMyuM1NHc7Ey0Y=
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    repo: Mykrobe-tools/mykrobe

notifications:
  email: false
