language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - brew update
    - brew tap mongodb/brew
    - brew update
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    - wget -O mykrobe-data.tar.gz https://bit.ly/2H9HKTU && tar -zxvf mykrobe-data.tar.gz && rm -fr src/mykrobe/data && mv mykrobe-data src/mykrobe/data
    - pip3 install .
    - pip3 install pyinstaller
    - git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex
    - cd mccortex
    - make
    - cd ../dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../

  - name: Windows Python 3.8.0
    os: windows
    language: shell
    before_install:
    - echo $PATH
    - which bash || echo "bash not found"
    - which make || echo "make not found"
    - which cc || echo "cc not found"
    - which gcc || echo "gcc not found"
    - ls -lh /bin/
    - ls -lh /c
    - choco install cygwin
    - ls -lh /c/tools/cygwin/
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip,bzip2,xz
    - choco install python --version 3.8.0
    - python -m pip install --upgrade pip
    - choco install mongodb
    #- choco install make
    #- choco install bzip2
    - find /c/ProgramData/chocolatey/ | sort
    #- p=$PWD
    #- cd ..
    #- mkdir xz
    #- cd xz
    #- wget https://tukaani.org/xz/xz-5.2.4-windows.zip
    #- unzip xz-5.2.4-windows.zip
    #- cp -rp include/* /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/include/
    #- cp bin_x86-64/liblzma.a /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/
    #- cd $p
    env:
    - PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - TOXENV=py38
    - CC=gcc
    before_deploy:
    - pip3 install pypiwin32
    - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
    - git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex
    - python ci/windows_xxhsum_fix.py
    - cd mccortex/libs/htslib/
    # Use older htslib release, which does not include <sys/socket.h>, which
    # breaks windows because it doesn't exist (windows uses winsock instead)
    - git checkout 1832d3a1b75133e55fb6abffc3f50f8a6ed5ceae
    - autoreconf
    - ./configure --disable-bz2
    - CPATH=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/:$CPATH make
    - cd ../../
    # To find bzlib.h, otherwise make fails
    - export C_INCLUDE_PATH=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/:$CPLUS_INCLUDE_PATH
    - export CPATH=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/:$CPATH
    - echo $CPATH
    - CPATH=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include/:$CPATH make
    - cd ../dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../

install:
- pip install cython
- travis_retry pip install tox
#script: tox -e $TOXENV
script: echo "Skipping tests"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NkTX3yLCZiJrSOIUwoGql9VdbTm5YkHoqaPbRytkOaRrr3LVl4jALKqrPopPfjMcHTKwGgJCq9Lr35XsTbnXKxEkaAe5UrBqiUJc6bcclX0zODwRCPZuLZ3GVcKPorRV75azPNEjW+pOjU72fIDNYTVLq+4+VmpI77rOfgoKYqsT9mjbhpMqpwST+YjgSOAv8Wr2WaUpaYxJyUxtsQXUMSZWhqheJBIfAdoWd7+MgqNYvK6lGzuvaVbFugv7pwzV8ZxxopW7A/LAKgoJrIdFaVbHg/iXHuWLPTZ4YocyWXWAEkUUNcUo5Ezg77PdPLox0HvZuIAJfgM129Pl6OCZeVeUxpI2Q1s770m72ULwMVTILLIkhhi6PCmNUbVxbdnqIZCHXf+kdicHeSLF9fxbMO7AIDX6D0ixQ/SWOVdHQVUZmoPCal2Lv2RPJvl+1clXUfKSPmX4Ht3v+z4OwwObAzb/cW2uB1djxzRtHD/bAs7XD692w9ddEcdiPp/MvEyC9jCwZ9T7o9z3tPjGPWepNRsUoKK2SqlFUcsLR97KEPP/jRPVUnqtPN8PvNLyFOvbyVFe8PZEqqtuVDftqFUEBsy8+NPaXI8/qcyg/hZO0M01JXIN5ILE+8W3eBqj4pHL8IveAXkiRS5SsSY791+N/0Ujoy5T3eMcQGPdoaTeWvA=
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx || $TRAVIS_OS_NAME = windows
    repo: martinghunt/mykrobe
